### PR TITLE
adjusted upper limit

### PR DESCRIPTION
**Pull request by prolixalias**

### CODE REVIEW

**Comment by op-ct** [comment]
@prolixalias I just noticed it's still using a 2017-era `.fixtures.yml` with outdated URL protocols an branch names, which will cause spec tests to fail, anyway.

I can't enter suggestions for files that aren't in the PR, but this `.fixtures.yml` works: 

```yaml
fixtures:
  repositories:
    "stdlib":
      "repo": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "main"
    "concat":
      "repo": "https://github.com/puppetlabs/puppetlabs-concat.git"
      "ref": "main"
    "hocon":
      "repo": "https://github.com/puppetlabs/puppetlabs-hocon.git"
      # NOTE: module is archived, so not using "main"
      "ref": "master"
  symlinks:
    "puppet_authorization": "#{source_dir}"
```

**Comment by chelnak** [comment]
@prolixalias I'm not sure who owns this or why it was un-archived.

I'll ask internally and see what comes up. Thanks for flagging.

**Comment by prolixalias** [comment]
Fixtures adjusted... Should I attempt to convert to GH actions based on another module? ntp perhaps? Or time better spent making travis-ci pass?

**Comment by trevor-vaughan** [comment]
@prolixalias Given that this is essentially a trivial change, I would suggest getting it released manually and then converting over to GH actions.

**Comment by kbucheli** [comment]
What is missing for this to be merged?

**Comment by olifre** [comment]
Are there any news on this PR or from the maintainers of the repository? Since this module is also missing Puppet 7 support (but in turn is a dependency of other modules such as [puppetlabs-node_encrypt](https://github.com/puppetlabs/puppetlabs-node_encrypt), it would be great to see this merged as a first step.

**Comment by h0tw1r3** [comment]
pipelines, fixtures, etc updated in #43

**Pull request closed without merging**
