### PR TITLE
Support Puppet 7

### PR DESCRIPTION
**Pull request by mattock**

### CODE REVIEW

**Comment by olifre** [comment]
It would be great if this module could indeed be bumped to support a non-EOL version of Puppet. This module is for example relied upon by [puppetlabs-node_encrypt](https://forge.puppet.com/modules/puppetlabs/node_encrypt).

**Comment by XMol** [comment]
Maybe instead ping about #37? That MR has had some more progress on the very same front. This PR should be closed in my humble opinion.

**Comment by olifre** [comment]
@XMol Indeed, the other PR is more advanced (but not (yet) bumping the Puppet version). I'll bump it, too.

**Comment by h0tw1r3** [comment]
Support added in #43

**Pull request closed without merging**
